# Generated by Django 3.2.4 on 2021-06-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('test', models.CharField(max_length=20)),
                ('pincode', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Signup Data',
            },
        ),
    ]
