# Generated by Django 3.2.4 on 2021-06-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupData',
            new_name='LabData',
        ),
        migrations.AlterModelTable(
            name='labdata',
            table='Lab Data',
        ),
    ]
