# Generated by Django 3.2.4 on 2021-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldata',
            name='test',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phoneNo',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
