# Generated by Django 3.2.4 on 2021-06-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0003_rename_name_hospitaldata_hospital_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='test_name',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='price',
            new_name='test_price',
        ),
    ]
