# Generated by Django 3.2.4 on 2021-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0004_auto_20210624_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('test_price', models.BigIntegerField()),
                ('hospital_id', models.ForeignKey(db_column='Hospital_ID', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='LoginSystem.hospitaldata')),
            ],
            options={
                'db_table': 'Book Slot',
            },
        ),
    ]
