# Generated by Django 3.2.4 on 2021-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0005_bookslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
