# Generated by Django 3.2.4 on 2021-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0006_bookslot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
