# Generated by Django 3.2.4 on 2021-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0008_alter_userdata_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.CharField(max_length=100),
        ),
    ]
